spring.application.name=miniAppLeaflet

spring.datasource.url=jdbc:postgresql://localhost:5432/bdd_mini_app_leaflet
spring.datasource.username=postgres
spring.datasource.password=613@Sql

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true